#! /bin/bash

#> synopsis: TODO: write down.
#> type: TODO: write down.
#> comment: TODO: write down.

targets_config=~/.config/gitwalker/targets.txt
GIT_STP=/tmp/git_steps

function main() {
	rm -f "$GIT_STP"
	touch "$GIT_STP"
	while read git_dir; do
		find "$git_dir" -type d -name ".git" | while read dir; do
			dir="${dir///\.git/}"
			status=$(git_check_uncommitted "${dir}")
			if $(test -n "$status"); then
				echo -e "${dir%.git}" >>/tmp/git_steps
			fi
		done
	done <<<$(expand_globs $targets_config)
}

main
