#! /bin/bash

#> synopsis: TODO: write down.
#> type: TODO: write down.
#> comment: TODO: write down.

HUB_DIR=$HOME/myroot/projdir/
GIT_STP=/tmp/git_steps

function fun_git_start() {
	rm -f "$GIT_STP"
	touch "$GIT_STP"
	find "$HUB_DIR" -type d -name ".git" | while read dir; do
		status=$(git_check "${dir//\.git/}")
		if $(test -n "$status"); then
			echo -e "${dir%.git}" >>/tmp/git_steps
		fi
	done
}

fun_git_start
