#! /bin/bash

#> synopsis: TODO: write down.
#> type: TODO: write down.
#> comment: TODO: write down.

GIT_STP=/tmp/git_steps

function main() {
	rm -f "$GIT_STP"
	touch "$GIT_STP"
	while read git_dir; do
		find "$git_dir" -type d -name ".git" | while read dir; do
			status=$(git_check "${dir//\.git/}")
			if $(test -n "$status"); then
				echo -e "${dir%.git}" >>/tmp/git_steps
			fi
		done
	done <~/.config/gitwalker/targets.txt
}

main
