#! /bin/bash

#> synopsis: TODO: write down.
#> type: TODO: write down.
#> comment: TODO: write down.

function main() {
	find "$@" -type d -name ".git" | while read dir; do
		dir="${dir///\.git/}"
		status_uncommit=$(git_check_uncommitted "${dir}")
		status_unpushed=$(git_check_unpushed "${dir}")
		status_noremote=$(git_check_noremote "${dir}")

		has_error=0
		attributes=''

		# check uncommited flag.
		if $(test -n "$status_uncommit"); then
			has_error=$(($has_error + 1))
			attributes="${attributes}C"
		else
			attributes="${attributes} "
		fi

		# check unpushed flag.
		if $(test -n "$status_unpushed"); then
			has_error=$(($has_error + 1))
			attributes="${attributes}P"
		else
			attributes="${attributes} "
		fi

		# check noremote flag.
		if $(test -z "$status_noremote"); then
			has_error=$(($has_error + 1))
			attributes="${attributes}R"
		else
			attributes="${attributes} "
		fi

		if $(test $has_error -ne 0); then
			echo "${attributes} ${dir}"
		fi
	done
}

main "$@"
