#! /bin/bash

#> synopsis: TODO: write down.
#> type: TODO: write down.
#> comment: TODO: write down.

function main() {
	find "$@" -type d -name ".git" | while read dir; do
		dir="${dir///\.git/}"
		status=$(git_check "${dir}")
		if $(test -n "$status"); then
			#echo -e "${dir}\n${status}"
			echo -e "${dir}"
		fi
	done
}

main "$@"
